export const newUserStub = () => ({
  id: 'faef5492-0aa6-46e0-8bdb-470c42546dc3',
  email: '123@gmail.com',
  name: 'William',
  age: null,
  description: null,
  distance: null,
  interests: [],
  isActivated: false,
  nickname: null,
  pairsCount: 0,
  pictures: [],
  place: null,
  preferAgeFrom: null,
  preferAgeTo: null,
  preferSex: null,
  sex: null,
  usersOnlyInDistance: false,
});
