apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-demo-certificate
spec:
  isCA: true
  commonName: frontend-demo.com
  secretName: frontend-demo-tls
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: frontend-issuer
    kind: Issuer
    group: cert-manager.io
