apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-demo-deployment
  labels:
    app: frontend-demo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-demo-app-deployment
  template:
    metadata:
      labels:
        app: frontend-demo-app-deployment
    spec:
      containers:
        - name: frontend-demo-app-deployment
          image: stepasha419a/ducks-tinder-client-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
