apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-demo-deployment
  labels:
    app: frontend-demo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-demo-app-deployment
  template:
    metadata:
      labels:
        app: frontend-demo-app-deployment
    spec:
      containers:
        - name: frontend-demo-app-deployment
          image: stepasha419a/ducks-tinder-client-demo:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.125'
              memory: '128Mi'
            requests:
              cpu: '0.0625'
              memory: '64Mi'
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: tls-volume
              mountPath: /etc/nginx/cert/prod
              readOnly: true
            - name: config-volume
              mountPath: /usr/src/app/.env
              subPath: .env
              readOnly: true
      volumes:
        - name: tls-volume
          secret:
            secretName: frontend-demo-tls
        - name: config-volume
          secret:
            secretName: frontend-demo-secret
