apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: frontend-demo-secret
    files:
      - .env=frontend-demo-secret-template.env
    type: Opaque
generatorOptions:
  disableNameSuffixHash: true
