apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-certificate
  labels: 
    {{- include "ducks-tinder-client.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: {{ .Values.secret.serverName }}
  secretName: frontend-tls
  issuerRef:
    name: frontend-issuer
    kind: Issuer
    group: cert-manager.io