apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-external
  labels: 
    {{- include "ducks-tinder-client.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName:  {{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
