apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels: 
    {{- include "ducks-tinder-client.labels" . | nindent 4 }}
type: Opaque
data:
  VAR_MODE: {{ .Values.secret.mode | b64enc | quote }}
