apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels: 
    {{- include "ducks-tinder-client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: 
    {{ - include "ducks-tinder-client.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
