export * from './Chat/Chat';
export * from './Tinder/Tinder'
export * from './Profile/Profile'
export * from './Notifications/Notifications'
export * from './Forms/Login/LoginForm'
export * from './Forms/Registration/RegistrationForm'
export * from './Layout/Layout'
export * from './Pairs/Pairs'
export * from './Policy/Policy'