export * from './Chat/Chat';
export * from './Tinder/Tinder';
export * from './Profile/Profile';
export * from './Notifications/Notifications';
export * from './Forms/Login/Login';
export * from './Forms/Registration/Registration';
export * from './Layout/Layout';
export * from './Pairs/Pairs';
export * from './Policy/Policy';
export { Loading } from './Loading/Loading';
