name: build-arm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
          cache-image: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-cache
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
