name: continuous-integration

on: [push]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run lint:fix
        # TODO: replace with package scripts
        # TODO: maybe only check, without fix?
        run: pnpm nx run-many --target=lint:fix
      - name: Run prettier:fix
        run: pnpm nx run-many --target=prettier:fix
      - name: Run build
        run: pnpm nx run-many --target=build && pnpm run-many --target=prod
